name: shop_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.0.3
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.3
  equatable: ^2.0.7
  google_sign_in: ^6.2.1
  image_picker: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  awesome_snackbar_content: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icon/
    - assets/img/
