name: bloc_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.2
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  firebase_core: ^4.0.0
  google_sign_in: ^6.2.1
  loader_overlay: ^5.0.0
  awesome_snackbar_content: ^0.1.6
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^6.0.1
  equatable: ^2.0.7
  image_picker: ^1.2.0
  shop_core:
    path: ../shop_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
